site_name: Quillum Docs

nav:
  - Home: index.md
  - Backend:
    - Overview: backend/index.md
    - Architecture: backend/architecture/index.md
    - API Reference: backend/api/index.md
    - Authentication: backend/authentication/index.md
    - Database Schema: backend/database/index.md
    - Testing:
      - Overview: backend/testing/index.md
      - Integration Tests: backend/testing/integration_tests.md
    - Deployment: backend/deployment/index.md
  - Crawler:
    - Overview: crawler/index.md
    - Architecture: crawler/architecture.md
    - Configuration: crawler/configuration.md
    - Anti-Bot Measures: crawler/anti-bot.md
    - Elasticsearch Integration: crawler/elasticsearch.md
    - URL Deduplication: crawler/deduplication.md
    - Metrics: crawler/metrics.md
    - API: crawler/api.md

theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode